// <auto-generated />
using System;
using ChangeDataCapture.ApiService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeDataCapture.ApiService.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    partial class MoviesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChangeDataCapture.ApiService.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<decimal>("Ratting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0195bda1-76dc-76a2-a0c0-7159220ec134"),
                            Genre = 4,
                            Ratting = 0m,
                            ReleaseDate = new DateOnly(1999, 3, 31),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("0195bda1-76dc-7f46-89a1-75105b2d30d2"),
                            Genre = 4,
                            Ratting = 0m,
                            ReleaseDate = new DateOnly(2003, 5, 15),
                            Title = "The Matrix Reloaded"
                        },
                        new
                        {
                            Id = new Guid("0195bda1-76dc-7fdc-b9b3-b882c033b492"),
                            Genre = 4,
                            Ratting = 0m,
                            ReleaseDate = new DateOnly(2003, 11, 5),
                            Title = "The Matrix Revolutions"
                        },
                        new
                        {
                            Id = new Guid("0195bda1-76dc-735c-9361-cc0d0b311d7f"),
                            Genre = 2,
                            Ratting = 0m,
                            ReleaseDate = new DateOnly(1994, 9, 23),
                            Title = "The Shawshank Redemption"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
